services:
  tallybackend:
    # Use your Docker image name here
    image: goswamirohit/tallybackend:v1
    container_name: tallybackend
    restart: unless-stopped
    # Maps host port 8000 to the container's exposed port 8000 (from your Dockerfile)
    ports:
      - "8000:8000"
    # Tells Docker Compose to read environment variables from a .env file in the same directory
    env_file:
      - .env

    environment:
      - DATABASE_URL=${DATABASE_URL}